import { useState } from 'react'
import { Check, Copy, MessageSquare, Plus, Send, Trash2, Users } from 'lucide-react'
import { useEditorStore } from '../../../../store/editorStore'
import { uid } from '../../../../lib/defaults'
import { withWorkspace } from '../../lib/workspaceDefaults'
import { CustomSelect } from '../../../../components/ui/CustomSelect'
import { EmptyPanel, PanelHeader, SectionCard } from '../PanelPrimitives'
import type { Collaborator } from '../../../../types'

export function CollaborationPanel() {
  const state = useEditorStore()
  const workspace = withWorkspace(state.project.workspace)
  const [email, setEmail] = useState('')
  const [comment, setComment] = useState('')
  const [copied, setCopied] = useState(false)
  const invite = () => { if (!email.includes('@')) return; const collaborator: Collaborator = { id: uid('person'), name: email.split('@')[0], email, role: 'reviewer', status: 'invited' }; state.updateWorkspace((current) => ({ ...current, collaborators: [...current.collaborators, collaborator] }), `Invited ${email}`); setEmail('') }
  const addComment = () => { if (!comment.trim()) return; state.updateWorkspace((current) => ({ ...current, comments: [{ id: uid('comment'), author: 'You', body: comment.trim(), elementId: state.selectedIds[0], pageId: state.activePageId, resolved: false, createdAt: new Date().toISOString() }, ...current.comments] }), 'Added a review comment'); setComment('') }
  const copyReviewLink = async () => { await navigator.clipboard.writeText(`${location.origin}${location.pathname}#review=${state.project.id}`); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  return <div className="studio-panel">
    <PanelHeader title="Collaboration and review" description="Invite roles, annotate selected layers, resolve review threads, share project-specific review links, and inspect a bounded activity history." actions={<button className="button button-secondary" onClick={() => void copyReviewLink()}>{copied ? <Check size={14} /> : <Copy size={14} />} {copied ? 'Copied' : 'Copy review link'}</button>} />
    <div className="studio-two-column"><SectionCard title="People and roles" description="Backend sync adapters can promote invited collaborators into live multiplayer sessions."><div className="studio-inline-form"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="reviewer@example.com" /><button className="button button-primary" onClick={invite}><Plus size={14} /> Invite</button></div><div className="people-list">{workspace.collaborators.map((person) => <div key={person.id}><span className="avatar">{person.name.slice(0, 2).toUpperCase()}</span><div><strong>{person.name}</strong><small>{person.email || 'Local owner'} · {person.status}</small></div><CustomSelect label={`${person.name} role`} value={person.role} options={[{ value: 'owner', label: 'Owner' }, { value: 'editor', label: 'Editor' }, { value: 'reviewer', label: 'Reviewer' }, { value: 'viewer', label: 'Viewer' }]} disabled={person.id === 'owner'} onChange={(role) => state.updateWorkspace((current) => ({ ...current, collaborators: current.collaborators.map((item) => item.id === person.id ? { ...item, role: role as Collaborator['role'] } : item) }))} /></div>)}</div></SectionCard>
      <SectionCard title="Add comment" description={state.selectedIds[0] ? 'The comment will be pinned to the selected layer.' : 'The comment will be attached to the active page.'}><textarea rows={5} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Describe the requested change or decision…" /><button className="button button-primary" onClick={addComment}><Send size={14} /> Add comment</button></SectionCard></div>
    <SectionCard title="Review threads" description="Resolved comments remain in the activity trail until explicitly removed.">{!workspace.comments.length ? <EmptyPanel icon={<MessageSquare size={22} />} title="No review comments" description="Select a layer and leave focused feedback." /> : <div className="comment-list">{workspace.comments.map((item) => <div className={item.resolved ? 'is-resolved' : ''} key={item.id}><span className="avatar">{item.author.slice(0, 2).toUpperCase()}</span><div><strong>{item.author}</strong><p>{item.body}</p><small>{new Date(item.createdAt).toLocaleString()}</small></div><button className="button button-ghost" onClick={() => state.updateWorkspace((current) => ({ ...current, comments: current.comments.map((commentItem) => commentItem.id === item.id ? { ...commentItem, resolved: !commentItem.resolved } : commentItem) }))}>{item.resolved ? 'Reopen' : 'Resolve'}</button><button className="bare-icon" onClick={() => state.updateWorkspace((current) => ({ ...current, comments: current.comments.filter((commentItem) => commentItem.id !== item.id) }))}><Trash2 size={13} /></button></div>)}</div>}</SectionCard>
    <SectionCard title="Activity" description="The newest one hundred material workspace actions are retained.">{!workspace.activity.length ? <EmptyPanel icon={<Users size={22} />} title="No recorded activity" description="Component, asset, template, review, and deployment actions appear here." /> : <div className="activity-list">{workspace.activity.slice(0, 20).map((item) => <div key={item.id}><span /><div><strong>{item.actor}</strong><p>{item.action}</p></div><small>{new Date(item.createdAt).toLocaleString()}</small></div>)}</div>}</SectionCard>
  </div>
}
