import { useState } from 'react'
import { Database, FileInput, Plus, Table2, Trash2 } from 'lucide-react'
import { useEditorStore } from '../../../../store/editorStore'
import { uid } from '../../../../lib/defaults'
import { withWorkspace } from '../../lib/workspaceDefaults'
import { EmptyPanel, PanelHeader, SectionCard, StatusBadge } from '../PanelPrimitives'
import type { DataCollection, FormDefinition } from '../../../../types'

export function DataPanel() {
  const state = useEditorStore()
  const workspace = withWorkspace(state.project.workspace)
  const [collectionName, setCollectionName] = useState('')
  const [formName, setFormName] = useState('')
  const addCollection = () => {
    if (!collectionName.trim()) return
    const collection: DataCollection = { id: uid('collection'), name: collectionName.trim(), slug: collectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-'), fields: [{ id: uid('field'), name: 'Title', type: 'text', required: true }], records: [] }
    state.updateWorkspace((current) => ({ ...current, collections: [...current.collections, collection] }), `Created collection ${collection.name}`); setCollectionName('')
  }
  const addForm = () => {
    if (!formName.trim()) return
    const form: FormDefinition = { id: uid('form'), name: formName.trim(), fields: [{ id: uid('field'), label: 'Email', type: 'email', required: true }], successMessage: 'Thanks. Your response was received.', webhookUrl: '', submissions: [] }
    state.updateWorkspace((current) => ({ ...current, forms: [...current.forms, form] }), `Created form ${form.name}`); setFormName('')
  }
  return <div className="studio-panel">
    <PanelHeader title="Forms and data" description="Model reusable collections, dynamic records, validated forms, webhook delivery, and local submission previews without coupling the canvas to one backend." actions={<div className="studio-inline-meta"><StatusBadge tone="brand">{workspace.collections.length} collections</StatusBadge><StatusBadge tone="brand">{workspace.forms.length} forms</StatusBadge></div>} />
    <div className="studio-two-column"><SectionCard title="New collection" description="Collections can power repeated cards and future dynamic pages."><div className="studio-inline-form"><input value={collectionName} onChange={(event) => setCollectionName(event.target.value)} placeholder="Projects, Posts, Team" /><button className="button button-primary" onClick={addCollection}><Plus size={14} /> Create</button></div></SectionCard><SectionCard title="New form" description="Forms export with client validation and optional webhook delivery."><div className="studio-inline-form"><input value={formName} onChange={(event) => setFormName(event.target.value)} placeholder="Contact, Newsletter" /><button className="button button-primary" onClick={addForm}><Plus size={14} /> Create</button></div></SectionCard></div>
    <div className="studio-two-column"><SectionCard title="Collections" description="Add fields and sample records to define your content model.">{!workspace.collections.length ? <EmptyPanel icon={<Database size={22} />} title="No collections" description="Create a collection to model reusable content." /> : <div className="data-list">{workspace.collections.map((collection) => <div key={collection.id}><span><Table2 size={15} /></span><div><strong>{collection.name}</strong><small>/{collection.slug} · {collection.fields.length} fields · {collection.records.length} records</small></div><button className="button button-ghost" onClick={() => state.updateWorkspace((current) => ({ ...current, collections: current.collections.map((item) => item.id === collection.id ? { ...item, fields: [...item.fields, { id: uid('field'), name: `Field ${item.fields.length + 1}`, type: 'text', required: false }] } : item) }))}><Plus size={13} /> Field</button><button className="button button-ghost" onClick={() => state.updateWorkspace((current) => ({ ...current, collections: current.collections.map((item) => item.id === collection.id ? { ...item, records: [...item.records, { id: uid('record'), values: Object.fromEntries(item.fields.map((field) => [field.id, ''])) }] } : item) }))}><Plus size={13} /> Record</button><button className="button button-ghost" onClick={() => { state.addPage(`${collection.name} item`); const pageId = useEditorStore.getState().activePageId; if (pageId) useEditorStore.getState().updatePage(pageId, { dynamicCollectionId: collection.id }) }}><Plus size={13} /> Dynamic page</button><button className="bare-icon" onClick={() => state.updateWorkspace((current) => ({ ...current, collections: current.collections.filter((item) => item.id !== collection.id) }))}><Trash2 size={13} /></button></div>)}</div>}</SectionCard>
      <SectionCard title="Forms" description="Bind a form to the selected canvas layer, edit delivery, and inspect submission counts.">{!workspace.forms.length ? <EmptyPanel icon={<FileInput size={22} />} title="No forms" description="Create a validated form definition." /> : <div className="form-definition-list">{workspace.forms.map((form) => <div key={form.id}><div className="studio-card-header"><div><strong>{form.name}</strong><small>{form.fields.length} fields · {form.submissions.length} submissions</small></div><button className="bare-icon" onClick={() => state.updateWorkspace((current) => ({ ...current, forms: current.forms.filter((item) => item.id !== form.id) }))}><Trash2 size={13} /></button></div><label><span>Webhook URL</span><input value={form.webhookUrl} placeholder="https://api.example.com/forms" onChange={(event) => state.updateWorkspace((current) => ({ ...current, forms: current.forms.map((item) => item.id === form.id ? { ...item, webhookUrl: event.target.value } : item) }))} /></label><div className="studio-card-actions"><button className="button button-ghost" onClick={() => state.updateWorkspace((current) => ({ ...current, forms: current.forms.map((item) => item.id === form.id ? { ...item, submissions: [{ id: uid('submission'), createdAt: new Date().toISOString(), values: Object.fromEntries(item.fields.map((field) => [field.id, 'Sample response'])) }, ...item.submissions] } : item) }), `Captured test submission for ${form.name}`)}>Test submission</button><button className="button button-secondary" disabled={!state.selectedIds[0]} onClick={() => { const id = state.selectedIds[0]; if (id) state.updateElement(id, { type: 'form', formId: form.id }) }}>Bind selected layer</button></div></div>)}</div>}</SectionCard></div>
  </div>
}
